@echo off

SET VS2019VC_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
SET WINDDK_DIR=C:\WinDDK\7600.16385.1\bin\amd64

SET DEFAULT_DIR=C:\VBoxBuild

SET SDL_DIR=%DEFAULT_DIR%\SDL
SET SSL64_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win64
SET SSL32_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win32
SET CURL_DIR=%DEFAULT_DIR%\curl\curl-8.1.2

SET QT_DIR=%DEFAULT_DIR%\Qt\qt5-everywhere-src-5.15.2
SET QT_BUILD_DIR=%DEFAULT_DIR%\Qt\qt5-x64

SET VBOX_DIR=C:\VBoxBuild\VirtualBox
