@echo off

SET VS2019VC_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
SET WINDDK_DIR=C:\WinDDK\7600.16385.1\bin\amd64

SET DEFAULT_DIR=C:\VBoxBuild

SET SDL_DIR=%DEFAULT_DIR%\SDL
SET SSL64_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win64
SET SSL32_DIR=%DEFAULT_DIR%\SSL\OpenSSL-Win32
SET CURL_DIR=%DEFAULT_DIR%\curl\curl-8.0.1
SET VBOX_DIR=%DEFAULT_DIR%\VirtualBox
SET PYTHON_DIR=%userprofile%\AppData\Local\Programs\Python\Python311